<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="meedo74-ThinkPad-X230" failures="1" tests="1" name="add_to_cart_with_invalid_data" time="3.052" errors="0" timestamp="2024-01-22T00:08:44 EET">
  <testcase classname="testcases.T02_add_to_cart" name="add_to_cart_invalid" time="0.883">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [remove] but found [Add to cart]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [remove] but found [Add to cart]
at testcases.T02_add_to_cart.add_to_cart_invalid(T02_add_to_cart.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- add_to_cart_invalid -->
  <testcase classname="testcases.T02_add_to_cart" name="add_to_cart_valid" time="0.0">
    <ignored/>
  </testcase> <!-- add_to_cart_valid -->
</testsuite> <!-- add_to_cart_with_invalid_data -->
